# fly.toml app configuration file generated for lexique3-api on 2025-10-31T23:48:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lexique3-api'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  RUST_LOG = 'info'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/app/public'
  url_prefix = '/static/'
